import { PARAM_KEYS, type Params } from "./types";

export const PRESETS = {
  reset: {
    exposure: 0,
    contrast: 1,
    saturation: 1,
    temperature: 0,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0,
    vignette: 0,
    bloomThreshold: 0.8,
    bloomStrength: 0,
    bloomRadius: 0.4,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    fade: 0,
    highlights: 0,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
  },
  cinematic: {
    exposure: 0.1,
    contrast: 1.3,
    saturation: 0.85,
    temperature: -0.15,
    tint: 0,
    rgbShift: 0.002,
    grainIntensity: 0.08,
    vignette: 0.4,
    bloomThreshold: 0.85,
    bloomStrength: 0.3,
    bloomRadius: 0.5,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    fade: 0.02,
    highlights: -0.1,
    shadows: -0.15,
    shadowTone: 0,
    highlightTone: 0,
  },
  portra: {
    exposure: 0.2,
    contrast: 1.1,
    saturation: 0.9,
    temperature: 0.1,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0.12,
    vignette: 0.2,
    bloomThreshold: 0.7,
    bloomStrength: 0.15,
    bloomRadius: 0.3,
    halationIntensity: 0.25,
    halationSpread: 20,
    halationHue: 20,
    fade: 0.05,
    highlights: 0,
    shadows: 0.1,
    shadowTone: 0,
    highlightTone: 0,
  },
  gold200: {
    exposure: 0.15,
    contrast: 1.2,
    saturation: 1.15,
    temperature: 0.18,
    tint: 0,
    rgbShift: 0.001,
    grainIntensity: 0.1,
    vignette: 0.25,
    bloomThreshold: 0.75,
    bloomStrength: 0.2,
    bloomRadius: 0.35,
    halationIntensity: 0.15,
    halationSpread: 18,
    halationHue: 30,
    fade: 0.03,
    highlights: 0.05,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
  },
  pro400h: {
    exposure: 0.25,
    contrast: 1.05,
    saturation: 0.85,
    temperature: -0.1,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0.06,
    vignette: 0.15,
    bloomThreshold: 0.65,
    bloomStrength: 0.1,
    bloomRadius: 0.45,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    fade: 0.08,
    highlights: 0.05,
    shadows: 0.15,
    shadowTone: 0,
    highlightTone: 0,
  },
  bw: {
    exposure: 0.1,
    contrast: 1.4,
    saturation: 0,
    temperature: 0,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0.15,
    vignette: 0.5,
    bloomThreshold: 0.75,
    bloomStrength: 0.2,
    bloomRadius: 0.6,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    fade: 0.02,
    highlights: -0.1,
    shadows: -0.1,
    shadowTone: 0,
    highlightTone: 0,
  },
  ektar100: {
    exposure: 0.05,
    contrast: 1.25,
    saturation: 1.3,
    temperature: 0.02,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0.04,
    vignette: 0.15,
    bloomThreshold: 0.85,
    bloomStrength: 0.1,
    bloomRadius: 0.3,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    fade: 0,
    highlights: 0.1,
    shadows: -0.1,
    shadowTone: 0,
    highlightTone: 0,
  },
  superia400: {
    exposure: 0.1,
    contrast: 1.18,
    saturation: 1.08,
    temperature: -0.08,
    tint: 0,
    rgbShift: 0,
    grainIntensity: 0.1,
    vignette: 0.2,
    bloomThreshold: 0.8,
    bloomStrength: 0.1,
    bloomRadius: 0.35,
    halationIntensity: 0.1,
    halationSpread: 15,
    halationHue: 10,
    fade: 0.04,
    highlights: 0,
    shadows: 0.05,
    shadowTone: 0,
    highlightTone: 0,
  },
  cinestill800t: {
    exposure: 0.15,
    contrast: 1.15,
    saturation: 0.95,
    temperature: -0.3,
    tint: 0,
    rgbShift: 0.001,
    grainIntensity: 0.12,
    vignette: 0.3,
    bloomThreshold: 0.6,
    bloomStrength: 0.35,
    bloomRadius: 0.5,
    halationIntensity: 0.4,
    halationSpread: 25,
    halationHue: 15,
    fade: 0.03,
    highlights: -0.05,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
  },
} satisfies Record<string, Params>;

export type PresetName = keyof typeof PRESETS;

export const PRESET_BUTTONS: {
  name: PresetName;
  label: string;
  subtitle: string;
}[] = [
  { name: "cinematic", label: "Cinematic", subtitle: "Teal & Orange" },
  { name: "portra", label: "Portra", subtitle: "Warm Pastel" },
  { name: "gold200", label: "Gold 200", subtitle: "Saturated Warm" },
  { name: "pro400h", label: "Pro 400H", subtitle: "Cool Soft" },
  { name: "ektar100", label: "Ektar 100", subtitle: "Vivid Sharp" },
  { name: "superia400", label: "Superia", subtitle: "Cool Green" },
  { name: "cinestill800t", label: "CineStill", subtitle: "Tungsten Glow" },
  { name: "bw", label: "B&W", subtitle: "Classic Mono" },
  { name: "reset", label: "Reset", subtitle: "No Grade" },
];

/** Dehancer-style hue: 0 = deep red → 100 = orange-red */
export function halationHueToHex(hue: number): string {
  const t = Math.max(0, Math.min(1, hue / 100));
  const r = Math.round(0xe8 + (0xc8 - 0xe8) * t);
  const g = Math.round(0x10 + (0x60 - 0x10) * t);
  const b = Math.round(0x20 + (0x10 - 0x20) * t);
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

export function findMatchingPreset(params: Params): PresetName | null {
  for (const [name, preset] of Object.entries(PRESETS) as [PresetName, Params][]) {
    if (PARAM_KEYS.every((key) => preset[key] === params[key])) {
      return name;
    }
  }
  return null;
}
