export const config = {
  id: "AEBookCase01HelloHello1",
  fps: 30,
  width: 1920,
  height: 1080,
  totalFrames: 45,
  background: "#ffffff",
  bubbleFill: "#31b1aa",
  textColor: "#33073b",
  seedScale: 0.018,
  peakScale: 1.08,
  growFrames: 5,
  settleFrames: 7,
  bubbleWidth: 352,
  bubbleHeight: 188,
  textSize: 112,
  textLetterSpacingEm: -0.055,
  fontFamily: '"Arial Black", "Arial Bold", "Helvetica Neue", Arial, sans-serif',
  bubbles: [
    { key: "left", centerX: 338, centerY: 688, startFrame: 1 },
    { key: "center", centerX: 960, centerY: 688, startFrame: 5 },
    { key: "right", centerX: 1582, centerY: 688, startFrame: 9 },
  ],
} as const;

export type HelloBubbleSpec = (typeof config.bubbles)[number];

export interface HelloSpriteSpec {
  key: string;
  src: string;
  centerX: number;
  centerY: number;
  width: number;
  height: number;
  startFrame: number;
  layer: number;
}

export interface HelloSpriteHeroSpec extends HelloSpriteSpec {}

export interface HelloSplitHeroSpec {
  key: string;
  plateSrc: string;
  textSrc: string;
  centerX: number;
  centerY: number;
  width: number;
  height: number;
  startFrame: number;
  textStartFrame: number;
  textRevealFrames: number;
  layer: number;
}

export const hello2Config = {
  id: "AEBookCase01HelloHello2",
  fps: 30,
  width: 1920,
  height: 1080,
  totalFrames: 90,
  background: "#ffffff",
  heroSeedScale: 0.018,
  heroPeakScale: 1.06,
  heroGrowFrames: 7,
  heroSettleFrames: 10,
  crowdSeedScale: 0.018,
  crowdPeakScale: 1.05,
  crowdGrowFrames: 5,
  crowdSettleFrames: 8,
  hero: {
    key: "hero",
    centerX: 960,
    centerY: 528,
    width: 492,
    height: 262,
    textSize: 114,
    startFrame: 6,
    layer: 20,
  },
  crowd: [
    {
      key: "ola",
      src: "ae-book-case-01-hello/hello2/ola.png",
      centerX: 696.5,
      centerY: 757.5,
      width: 246,
      height: 256,
      startFrame: 22,
      layer: 10,
    },
    {
      key: "xin-chao",
      src: "ae-book-case-01-hello/hello2/xin-chao.png",
      centerX: 997.5,
      centerY: 762.5,
      width: 316,
      height: 166,
      startFrame: 18,
      layer: 11,
    },
    {
      key: "ciao",
      src: "ae-book-case-01-hello/hello2/ciao.png",
      centerX: 1259,
      centerY: 712,
      width: 209,
      height: 213,
      startFrame: 23,
      layer: 12,
    },
    {
      key: "hej",
      src: "ae-book-case-01-hello/hello2/hej.png",
      centerX: 364.5,
      centerY: 630.5,
      width: 166,
      height: 170,
      startFrame: 28,
      layer: 13,
    },
    {
      key: "buna-ziua",
      src: "ae-book-case-01-hello/hello2/buna-ziua.png",
      centerX: 418.5,
      centerY: 803.5,
      width: 282,
      height: 120,
      startFrame: 30,
      layer: 13,
    },
    {
      key: "konnichiwa",
      src: "ae-book-case-01-hello/hello2/konnichiwa.png",
      centerX: 1506.5,
      centerY: 771.5,
      width: 270,
      height: 184,
      startFrame: 29,
      layer: 13,
    },
    {
      key: "merhaba",
      src: "ae-book-case-01-hello/hello2/merhaba.png",
      centerX: 382.5,
      centerY: 347.5,
      width: 246,
      height: 256,
      startFrame: 26,
      layer: 24,
    },
    {
      key: "hola",
      src: "ae-book-case-01-hello/hello2/hola.png",
      centerX: 631,
      centerY: 329.5,
      width: 207,
      height: 212,
      startFrame: 14,
      layer: 24,
    },
    {
      key: "korean",
      src: "ae-book-case-01-hello/hello2/korean.png",
      centerX: 939.5,
      centerY: 300.5,
      width: 304,
      height: 130,
      startFrame: 22,
      layer: 25,
    },
    {
      key: "bonjour",
      src: "ae-book-case-01-hello/hello2/bonjour.png",
      centerX: 1262.5,
      centerY: 308.5,
      width: 256,
      height: 162,
      startFrame: 20,
      layer: 24,
    },
    {
      key: "chinese",
      src: "ae-book-case-01-hello/hello2/chinese.png",
      centerX: 1530.5,
      centerY: 338,
      width: 222,
      height: 227,
      startFrame: 27,
      layer: 24,
    },
    {
      key: "privet",
      src: "ae-book-case-01-hello/hello2/privet.png",
      centerX: 568.5,
      centerY: 530,
      width: 256,
      height: 161,
      startFrame: 16,
      layer: 25,
    },
    {
      key: "salve",
      src: "ae-book-case-01-hello/hello2/salve.png",
      centerX: 1342,
      centerY: 506.5,
      width: 276,
      height: 146,
      startFrame: 14,
      layer: 24,
    },
    {
      key: "halo",
      src: "ae-book-case-01-hello/hello2/halo.png",
      centerX: 1559.5,
      centerY: 597.5,
      width: 150,
      height: 150,
      startFrame: 28,
      layer: 24,
    },
  ],
} as const;

export const hello3Config = {
  id: "AEBookCase01HelloHello3",
  fps: 30,
  width: 1920,
  height: 1080,
  totalFrames: 90,
  background: "#ffffff",
  heroSeedScale: 0.018,
  heroPeakScale: 1.065,
  heroGrowFrames: 4,
  heroSettleFrames: 6,
  crowdSeedScale: 0.018,
  crowdPeakScale: 1.05,
  crowdGrowFrames: 5,
  crowdSettleFrames: 8,
  hero: {
    key: "hero",
    src: "ae-book-case-01-hello/hello3/01_Hello1-hero.png",
    centerX: 960,
    centerY: 528,
    width: 485,
    height: 329,
    startFrame: 48,
    layer: 20,
  },
  crowd: [
    {
      key: "salve",
      src: "ae-book-case-01-hello/hello2/salve.png",
      centerX: 1342,
      centerY: 506.5,
      width: 276,
      height: 146,
      startFrame: 6,
      layer: 24,
    },
    {
      key: "hola",
      src: "ae-book-case-01-hello/hello2/hola.png",
      centerX: 631,
      centerY: 329.5,
      width: 207,
      height: 212,
      startFrame: 10,
      layer: 24,
    },
    {
      key: "privet",
      src: "ae-book-case-01-hello/hello2/privet.png",
      centerX: 568.5,
      centerY: 530,
      width: 256,
      height: 161,
      startFrame: 12,
      layer: 25,
    },
    {
      key: "xin-chao",
      src: "ae-book-case-01-hello/hello2/xin-chao.png",
      centerX: 997.5,
      centerY: 762.5,
      width: 316,
      height: 166,
      startFrame: 14,
      layer: 11,
    },
    {
      key: "bonjour",
      src: "ae-book-case-01-hello/hello2/bonjour.png",
      centerX: 1262.5,
      centerY: 308.5,
      width: 256,
      height: 162,
      startFrame: 15,
      layer: 24,
    },
    {
      key: "ola",
      src: "ae-book-case-01-hello/hello2/ola.png",
      centerX: 696.5,
      centerY: 757.5,
      width: 246,
      height: 256,
      startFrame: 18,
      layer: 10,
    },
    {
      key: "korean",
      src: "ae-book-case-01-hello/hello2/korean.png",
      centerX: 939.5,
      centerY: 300.5,
      width: 304,
      height: 130,
      startFrame: 18,
      layer: 25,
    },
    {
      key: "merhaba",
      src: "ae-book-case-01-hello/hello2/merhaba.png",
      centerX: 382.5,
      centerY: 347.5,
      width: 246,
      height: 256,
      startFrame: 21,
      layer: 24,
    },
    {
      key: "chinese",
      src: "ae-book-case-01-hello/hello2/chinese.png",
      centerX: 1530.5,
      centerY: 338,
      width: 222,
      height: 227,
      startFrame: 22,
      layer: 24,
    },
    {
      key: "ciao",
      src: "ae-book-case-01-hello/hello2/ciao.png",
      centerX: 1259,
      centerY: 712,
      width: 209,
      height: 213,
      startFrame: 23,
      layer: 12,
    },
    {
      key: "halo",
      src: "ae-book-case-01-hello/hello2/halo.png",
      centerX: 1559.5,
      centerY: 597.5,
      width: 150,
      height: 150,
      startFrame: 24,
      layer: 24,
    },
    {
      key: "hej",
      src: "ae-book-case-01-hello/hello2/hej.png",
      centerX: 364.5,
      centerY: 630.5,
      width: 166,
      height: 170,
      startFrame: 26,
      layer: 13,
    },
    {
      key: "konnichiwa",
      src: "ae-book-case-01-hello/hello2/konnichiwa.png",
      centerX: 1506.5,
      centerY: 771.5,
      width: 270,
      height: 184,
      startFrame: 28,
      layer: 13,
    },
    {
      key: "buna-ziua",
      src: "ae-book-case-01-hello/hello2/buna-ziua.png",
      centerX: 418.5,
      centerY: 803.5,
      width: 282,
      height: 120,
      startFrame: 31,
      layer: 13,
    },
  ],
} as const;

export const hello4Config = {
  id: "AEBookCase01HelloHello4",
  fps: 30,
  width: 1920,
  height: 1080,
  totalFrames: 90,
  background: "#ffffff",
  heroSeedScale: 0.018,
  heroPeakScale: 1.05,
  heroGrowFrames: 6,
  heroSettleFrames: 6,
  crowdSeedScale: hello3Config.crowdSeedScale,
  crowdPeakScale: hello3Config.crowdPeakScale,
  crowdGrowFrames: hello3Config.crowdGrowFrames,
  crowdSettleFrames: hello3Config.crowdSettleFrames,
  hero: {
    key: "hero",
    plateSrc: "ae-book-case-01-hello/hello4/01_Hello1-hero-plate.png",
    textSrc: "ae-book-case-01-hello/hello4/01_Hello1-hero-text.png",
    centerX: 960,
    centerY: 528,
    width: 485,
    height: 329,
    startFrame: 48,
    textStartFrame: 51,
    textRevealFrames: 7,
    layer: 20,
  },
  crowd: hello3Config.crowd,
} as const;

export type HelloSpriteBubbleSpec = (typeof hello2Config.crowd)[number];
export type Hello2HeroSpec = typeof hello2Config.hero;
export type Hello3SpriteBubbleSpec = (typeof hello3Config.crowd)[number];
export type Hello3HeroSpec = typeof hello3Config.hero;
export type Hello4SpriteBubbleSpec = (typeof hello4Config.crowd)[number];
export type Hello4HeroSpec = typeof hello4Config.hero;
